version: '2'
services:
  web:
    container_name: "SvelteNode"
    image: node:20-alpine3.17
    #user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes: 
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - "3001:3000"
    command: "npm run dev"
    #restart: always
    #deploy:
      #restart_policy:
      #  condition: any
      #  delay: 5s

